### ISSUE TITLE
.NET Framework 4.0

### ISSUE THREAD

**Issue by betrisey** [GHPReporter/Ghpr.Core#35]
Hi,
I would like to use Ghpr.Core and Ghpr.NUnit in a .NET 4.0 project but the nuget package is only available for 4.5.
I tried to change the target framework to 4.0 and was able to build it.

Do you think that's possible to lower the target framework?
Otherwise I can create a pull request to target both frameworks. (https://shazwazza.com/post/multi-targeting-a-single-net-project-to-build-for-different-framework-versions/)

Thanks a lot for this great library!

**Comment by elv1s42** [comment]
Hi @betrisey 
I think the good idea is to target both frameworks.
The only problem that we may face is to improve the way of building new NuGet packages, as now they are published automatically via AppVeyor after commit into 'nuget' branch. So it may be not very easy to do (just because I've never tried it).

**Comment by elv1s42** [comment]
@betrisey, I merged your pull request, but there is one prombem I think. There is an error message:
<img width="743" alt="2017-03-24 14_41_47-ghpr core 1 0 286 - appveyor" src="https://cloud.githubusercontent.com/assets/6689884/24292854/14f05566-10a0-11e7-9edb-4472504da2d7.png">


I can see the same messages in your build too: https://ci.appveyor.com/project/betrisey/ghpr-core/build/1.0.8/messages
